# Generated by Django 4.2 on 2023-04-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=16)),
                ('expire', models.CharField(max_length=5)),
            ],
        ),
    ]
